import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { chmod, mkdtemp, mkdir, readFile, rename, rm, symlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import test from 'node:test';

import { invokeClaudeNativeRoutingSession } from './claude-native-session.js';

const posixOnly = { skip: process.platform === 'win32' ? 'owned POSIX native Hook transport unavailable' : false };

function sha(value) { return `sha256:${createHash('sha256').update(value).digest('hex')}`; }

function nativeHook(settings, request, payload) {
  const command = settings.hooks[payload.hook_event_name][0].hooks[0].command;
  const response = spawnSync('/bin/sh', ['-c', command], { cwd: request.cwd, env: request.env,
    input: JSON.stringify(payload), encoding: 'utf8', timeout: 2000, maxBuffer: 65536 });
  assert.equal(response.error, undefined);
  assert.equal(response.status, 0, response.stderr);
  assert.equal(response.stderr, '');
  return JSON.parse(response.stdout);
}

test('native routing invocation captures its actual project sources and hands native journal materialization to its public observation without loaded authority (external process double)', posixOnly, async t => {
  const root = await mkdtemp(path.join(tmpdir(), 'native-routing-materialization-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = path.join(root, 'home');
  const cwd = path.join(root, 'fixture/repository');
  const canonicalRoot = path.join(cwd, '.agents/skills/deployment');
  const aliasRoot = path.join(cwd, '.claude/skills/deployment');
  const source = '---\nname: deployment\ndescription: Prepare an owned deployment checklist.\n---\nOnly select; do not deploy.\n$ARGUMENTS\n';
  const motherSkillRoot = path.join(home, '.claude/skills/agent-init');
  await mkdir(canonicalRoot, { recursive: true });
  await mkdir(path.dirname(aliasRoot), { recursive: true });
  await mkdir(motherSkillRoot, { recursive: true });
  await symlink('../../.agents/skills/deployment', aliasRoot);
  await writeFile(path.join(canonicalRoot, 'SKILL.md'), source);
  await writeFile(path.join(motherSkillRoot, 'SKILL.md'), 'Mother source is not routing authority.\n');
  const request = { phase: 'routing', id: 'deployment-test', kind: 'implicit', sessionId: randomUUID(),
    prompt: 'Prepare a staging deployment checklist for this owned fixture.', cwd,
    contributors: [{ fixtureId: '15-deployment', cwd }], discoveryDirectories: [cwd], motherSkillRoot,
    history: [], resume: false, profile: { readOnly: true }, harnessVersion: '2.1.285' };
  const env = { HOME: home, CLAUDE_CONFIG_DIR: path.join(home, '.claude'), PATH: process.env.PATH };
  let calls = 0;
  const observed = await invokeClaudeNativeRoutingSession({ root, home, request, command: process.execPath,
    model: 'local-process-double', env, executionKind: 'test-double', invoke: async input => {
      calls++;
      const settings = JSON.parse(await readFile(input.args[input.args.indexOf('--settings') + 1], 'utf8'));
      const journalFile = path.join(home, '.claude/projects/owned-routing', `${request.sessionId}.jsonl`);
      await mkdir(path.dirname(journalFile), { recursive: true });
      const common = { session_id: request.sessionId, cwd, transcript_path: journalFile };
      assert.deepEqual(nativeHook(settings, input, { ...common, hook_event_name: 'SessionStart' }), {});
      const toolInput = { skill: 'deployment', args: 'staging' };
      const tool = { ...common, tool_use_id: 'route_skill_1', tool_name: 'Skill', tool_input: toolInput };
      assert.deepEqual(nativeHook(settings, input, { ...tool, hook_event_name: 'PreToolUse' }), {});
      assert.deepEqual(nativeHook(settings, input, { ...tool, hook_event_name: 'PostToolUse',
        tool_response: { success: true, commandName: 'deployment', status: 'inline' } }), {});
      assert.deepEqual(nativeHook(settings, input, { ...common, hook_event_name: 'Stop' }), {});
      const callUuid = randomUUID();
      const frameUuid = randomUUID();
      // Native frames are an independent literal, not generated by the producer.
      const journal = [
        { type: 'assistant', uuid: callUuid, parentUuid: null, sessionId: request.sessionId, cwd, version: '2.1.285',
          message: { role: 'assistant', content: [{ type: 'tool_use', id: 'route_skill_1', name: 'Skill', input: toolInput }] } },
        { type: 'user', uuid: frameUuid, parentUuid: callUuid, sessionId: request.sessionId, cwd, version: '2.1.285',
          isMeta: true, turnCompanion: true, sourceToolUseID: 'route_skill_1', message: { role: 'user', content: [{ type: 'text',
            text: `Base directory for this skill: ${aliasRoot}\n\nOnly select; do not deploy.\nstaging\n` }] } },
      ];
      await writeFile(journalFile, journal.map(JSON.stringify).join('\n') + '\n');
      return { status: 0, stdout: [
        { type: 'system', subtype: 'init', session_id: request.sessionId, tools: ['Skill'] },
        { type: 'assistant', session_id: request.sessionId, message: journal[0].message },
        { type: 'user', session_id: request.sessionId, message: { content: [{ type: 'tool_result', tool_use_id: 'route_skill_1', content: 'Launching skill: deployment' }] } },
        { type: 'user', session_id: request.sessionId, uuid: frameUuid, isSynthetic: true, message: journal[1].message },
        { type: 'result', subtype: 'success', is_error: false, session_id: request.sessionId, permission_denials: [] },
      ].map(JSON.stringify).join('\n') + '\n' };
    } });
  assert.equal(calls, 1);
  assert.equal(observed.observation.status, 'blocked', observed.observation.code);
  assert.equal(observed.observation.code, 'NATIVE_SELECTION_UNVERIFIED');
  const proof = observed.observation.provenance;
  assert.equal(proof.exactSourceMaterializationMatched, true);
  const [materialization] = proof.sourceMaterializations;
  assert.equal(materialization.command, 'deployment');
  assert.equal(materialization.namespace, 'project');
  assert.equal(materialization.sourceFileDigest, sha(source));
  assert.equal(materialization.aliasRootRef, '<owned-root>/fixture/repository/.claude/skills/deployment');
  assert.equal(materialization.sourceRootRef, '<owned-root>/fixture/repository/.agents/skills/deployment');
  assert.equal(materialization.journalRef, `<owned-root>/home/.claude/projects/owned-routing/${request.sessionId}.jsonl`);
  assert.equal(materialization.branch, 'tool-skill');
  assert.equal(materialization.streamFrameMatched, true);
  for (const claim of ['selectionProtocolVerified', 'hookCoverageProven', 'permissionFloorProven']) assert.equal(proof[claim], false);
  assert.equal(proof.loaded, undefined);
  assert.equal(observed.qualification, 'unqualified');
  assert.equal(observed.liveSkillBehaviorProven, false);
  assert.equal(observed.invocation.corpusPromptUnchanged, true);
  const retained = JSON.stringify(observed.observation);
  for (const privateValue of [root, source, 'Base directory for this skill:']) assert.equal(retained.includes(privateValue), false);

  // Source/config failures stay on the pre-invoke side of the same public seam.
  let forbiddenCalls = 0;
  const rejected = (altered, environment, code) => assert.rejects(invokeClaudeNativeRoutingSession({ root, home,
    request: { ...request, sessionId: randomUUID(), ...altered }, command: process.execPath, model: 'local-process-double',
    env: environment, executionKind: 'test-double', invoke: async () => { forbiddenCalls++; return { status: 0 }; } }), { code });
  await rejected({}, { ...env, CLAUDE_CONFIG_DIR: path.join(root, 'alternate-config') }, 'NATIVE_ROUTING_SCOPE');
  await rejected({ harnessVersion: '2.1.286' }, env, 'NATIVE_MATERIALIZATION_PROFILE_UNSUPPORTED');
  await chmod(path.join(canonicalRoot, 'SKILL.md'), 0o666);
  await rejected({}, env, 'NATIVE_MATERIALIZATION_SOURCE_INVALID');
  assert.equal(forbiddenCalls, 0);
  await chmod(path.join(canonicalRoot, 'SKILL.md'), 0o644);

  const emptyCwd = path.join(root, 'empty-fixture');
  await mkdir(emptyCwd);
  const emptyRequest = { ...request, cwd: emptyCwd, contributors: [{ fixtureId: 'empty-fixture', cwd: emptyCwd }],
    discoveryDirectories: [emptyCwd], sessionId: randomUUID() };
  const empty = await invokeClaudeNativeRoutingSession({ root, home, request: emptyRequest, command: process.execPath,
    model: 'local-process-double', env, executionKind: 'test-double', invoke: async input => {
      const settings = JSON.parse(await readFile(input.args[input.args.indexOf('--settings') + 1], 'utf8'));
      const transcript = path.join(home, '.claude/projects/owned-routing', `${emptyRequest.sessionId}.jsonl`);
      const common = { session_id: emptyRequest.sessionId, cwd: emptyCwd, transcript_path: transcript };
      nativeHook(settings, input, { ...common, hook_event_name: 'SessionStart' });
      nativeHook(settings, input, { ...common, hook_event_name: 'Stop' });
      await writeFile(transcript, '');
      return { status: 0, stdout: [
        { type: 'system', subtype: 'init', session_id: emptyRequest.sessionId, tools: ['Skill'] },
        { type: 'result', subtype: 'success', is_error: false, session_id: emptyRequest.sessionId, permission_denials: [] },
      ].map(JSON.stringify).join('\n') + '\n' };
    } });
  assert.equal(empty.observation.status, 'blocked');
  assert.equal(empty.observation.code, 'NATIVE_SELECTION_UNVERIFIED');
  assert.equal(empty.observation.provenance.sourceMaterializations, undefined);
  assert.equal(empty.observation.provenance.loaded, undefined);
  assert.equal(empty.observation.provenance.hookCoverageProven, false);
});

test('fresh native routing uses only selected contributor directories and cannot execute deployment commands (session double)', posixOnly, async t => {
  const root = await mkdtemp(path.join(tmpdir(), 'claude-routing-invocation-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = path.join(root, 'home');
  const cwd = path.join(root, 'fixture/repository');
  const canonicalSkill = path.join(cwd, '.agents/skills/deployment');
  await mkdir(canonicalSkill, { recursive: true });
  await mkdir(path.join(cwd, '.claude/skills'), { recursive: true });
  await symlink('../../.agents/skills/deployment', path.join(cwd, '.claude/skills/deployment'));
  await writeFile(path.join(canonicalSkill, 'SKILL.md'), '---\nname: deployment\ndescription: Explain the owned deployment workflow.\n---\nOnly select; do not deploy.\n');
  const motherSkillRoot = path.join(home, '.claude/skills/agent-init');
  await mkdir(motherSkillRoot, { recursive: true });
  await writeFile(path.join(motherSkillRoot, 'SKILL.md'), '---\nname: agent-init\ndescription: Initialize Agent configuration.\n---\nSetup only.\n');
  const request = { phase: 'routing', id: 'deployment-test', kind: 'implicit', sessionId: randomUUID(),
    prompt: 'Prepare the staging deployment checklist for this owned fixture.', cwd,
    contributors: [{ fixtureId: '15-deployment', cwd }], discoveryDirectories: [cwd], motherSkillRoot,
    history: [], resume: false, profile: { readOnly: true }, harnessVersion: '2.1.285' };
  let forbiddenCalls = 0;
  for (const invalid of [
    { ...request, harnessVersion: undefined },
    { ...request, history: ['setup context'] },
    { ...request, discoveryDirectories: [root] },
    { ...request, cwd: home },
    { ...request, sessionId: '../reused-session' },
  ]) await assert.rejects(invokeClaudeNativeRoutingSession({ root, home, request: invalid, command: process.execPath,
    model: 'session-double-model', env: { HOME: home, CLAUDE_CONFIG_DIR: path.join(home, '.claude'), PATH: process.env.PATH },
    executionKind: 'test-double', invoke: async () => { forbiddenCalls++; return { status: 0 }; } }), { code: 'NATIVE_ROUTING_SCOPE' });
  assert.equal(forbiddenCalls, 0);
  let invoked;
  const session = await invokeClaudeNativeRoutingSession({ root, home, request, command: process.execPath,
    model: 'session-double-model', env: { HOME: home, CLAUDE_CONFIG_DIR: path.join(home, '.claude'), PATH: process.env.PATH },
    executionKind: 'test-double', invoke: async input => {
      invoked = input;
      const arg = flag => input.args[input.args.indexOf(flag) + 1];
      assert.equal(arg('--tools'), 'Skill');
      assert.equal(arg('--permission-mode'), 'dontAsk');
      assert.equal(arg('--setting-sources'), 'project');
      assert.equal(input.args.includes('--restricted'), false);
      assert.equal(input.args.includes('--bare'), false);
      assert.equal(input.args.includes('--resume'), false);
      assert.equal(arg('--session-id'), request.sessionId);
      assert.equal(arg('--mcp-config'), '{"mcpServers":{}}');
      assert.equal(input.args.at(-1), request.prompt);
      assert.match(arg('--append-system-prompt'), /Do not execute/);
      const settings = JSON.parse(await readFile(arg('--settings'), 'utf8'));
      assert.ok(settings.hooks.PreToolUse);
      return { status: 0, stdout: [
        { type: 'system', subtype: 'init', session_id: request.sessionId, tools: ['Skill'] },
        { type: 'result', subtype: 'success', is_error: false, session_id: request.sessionId, permission_denials: [] },
      ].map(JSON.stringify).join('\n') + '\n' };
    } });
  assert.equal(invoked.cwd, cwd);
  assert.equal(session.processResult.status, 0);
  assert.equal(session.closed, true);
  assert.equal(session.observation.status, 'error');
  assert.equal(session.observation.code, 'NATIVE_EVENTS_MISSING');
  assert.equal(session.observation.loaded, undefined);
  assert.equal(session.qualification, 'unqualified');
  assert.equal(session.invocation.corpusPromptUnchanged, true);
  assert.match(session.invocation.promptDigest, /^sha256:[a-f0-9]{64}$/);
  assert.match(session.invocation.systemInstructionDigest, /^sha256:[a-f0-9]{64}$/);

  const outside = await mkdtemp(path.join(tmpdir(), 'claude-routing-unowned-'));
  t.after(() => rm(outside, { recursive: true, force: true }));
  const rejected = async (altered, code) => {
    let escapedCalls = 0;
    await assert.rejects(invokeClaudeNativeRoutingSession({ root, home, request: { ...request, sessionId: randomUUID(), ...altered },
      command: process.execPath, model: 'session-double-model', env: {}, executionKind: 'test-double',
      invoke: async () => { escapedCalls++; return { status: 0, stdout: '' }; } }), { code });
    assert.equal(escapedCalls, 0);
  };
  await rejected({ motherSkillRoot: outside }, 'NATIVE_ROUTING_SCOPE');
  await writeFile(path.join(canonicalSkill, 'SKILL.md'), '---\nname: deployment\ndescription: Owned selection.\nhooks: {}\n---\nNo actions.\n');
  await rejected({}, 'NATIVE_SKILL_INVENTORY_INVALID');
  await writeFile(path.join(canonicalSkill, 'SKILL.md'), '---\nname: deployment\ndescription: Owned selection.\n---\nNo actions.\n');
  await writeFile(path.join(cwd, '.claude/settings.json'), '{"hooks":{}}');
  await rejected({}, 'NATIVE_PROJECT_CONFIG_UNSUPPORTED');
  await rename(path.join(cwd, '.claude/settings.json'), path.join(root, 'retained-settings.json'));
  await mkdir(path.join(outside, 'skills/deployment'), { recursive: true });
  await writeFile(path.join(outside, 'skills/deployment/SKILL.md'), '---\nname: deployment\ndescription: Out-of-scope Skill.\n---\nNo actions.\n');
  await rename(path.join(cwd, '.agents'), path.join(cwd, '.agents-retained'));
  await symlink(outside, path.join(cwd, '.agents'));
  await rejected({}, 'NATIVE_SKILL_INVENTORY_INVALID');
});
